config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get 'tags/:tag', to: 'posts#index', as: :tag

  resources :posts
  resources :users

  get 'posts/index'

  root 'posts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ActiveRecord::Base
  acts_as_taggable
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  #before_action :current_user

  # GET /posts
  # GET /posts.json
  def index
    byebug
    if current_user.nil?
      redirect_to new_user_session_path
    else
      if params[:tag]
        @posts = Post.tagged_with(params[:tag]).order(created_at: :desc).where(user_id: current_user.id)
      else
        @posts = Post.order(created_at: :desc).where(user_id: current_user.id)
      end
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    
    unless current_user.nil?
      @user = current_user
      @post.user_id = @user.id
    end

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to posts_url, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body, :tag_list)
    end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
 
  def create
    self.resource = resource_class.find_for_authentication(sign_in_params.except(:password, :otp_response_code))
    if resource
      if resource.active_for_authentication?
        if resource && resource.otp_module_disabled?
          continue_sign_in(resource, resource_name)
        elsif resource && resource.otp_module_enabled?
          if params[:user][:otp_response_code].present?
            if resource.authenticate_otp(params[:user][:otp_response_code])
              sign_in(resource, scope: :user)
              continue_sign_in(resource, resource_name)
            else
              if resource.otp_counter < 5
                resource.increment!(:otp_counter)
                render 'two_factors_authentication' and sign_out(resource)
              end
            end
          else
            # wrong password or failed login should get back to login page
            if resource.valid_password?(params[:user][:password])
              render 'two_factors_authentication' and sign_out(resource)
            else
              sign_out(resource)
              respond_with resource, location: new_user_session_path 
            end
          end    
        end
      end
    end
  end
  
  private
  
  def continue_sign_in(resource, resource_name)
    self.resource = warden.authenticate!(auth_options)
    set_flash_message(:notice, :signed_in)
    sign_in(resource_name, resource)
    resource.update_column(:last_action_at,Time.now)
    yield resource if block_given?
    if  params[:redirect_to_path].present?
      respond_with resource, location: params[:redirect_to_path]
    else
      respond_with resource, location: after_sign_in_path_for(resource)
    end
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def activate_2fa
    qrcode = RQRCode::QRCode.new(current_user.provisioning_uri(nil, issuer: 'your-app-url.com'), :size => 12, :level => :h)
    @svg = qrcode.as_svg(offset: 0, color: '000', 
                    shape_rendering: 'crispEdges', 
                    module_size: 4)   
    respond_to :html
  end

  def activate_2fa_update
    if secure_params.key?(:otp_response_code)
      if @user.authenticate_otp(secure_params[:otp_response_code])
        @user.otp_module_enabled!
        # do something here
      else
        # do something here
      end
    else
      #turn off 2FA
      @user.otp_module_disabled!
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/_header.html.erb
	<header class="navbar navbar-fixed-top">
		<div class="container">
			<%= link_to "ramblings", root_path, id: "logo" %>
			<nav>
				<ul class="nav navbar-nav navbar-right">
					<li><%= link_to "home", posts_path %></li>
					<% if logged_in? %>
						<li><%= link_to "users", users_path %></li>
						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown">account <b class="caret"></b></a>
							<ul class="dropdown-menu">
								<li><%= link_to "profile", current_user %></li>
								<li><%= link_to "settings", '#' %></li>
								<li class="divider"></li>
								<li>
									<%= link_to "log out", logout_path, method: "delete" %>
								</li>
							</ul>
						</li>
					<% else %>
					<li><%= link_to "login", new_user_session_path %></li>
					<li><%= link_to "sign up", new_user_registration_path %></li>
					<% end %>
				</ul>
			</nav>
		</div>
	</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ramblings</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render 'layouts/header'%>
	<div class="container">
		<% if notice %>
		  <p class="alert alert-success"><%= notice %></p>
		<% end %>
		<% if alert %>
		  <p class="alert alert-danger"><%= alert %></p>
		<% end %>
		<%= yield %>
	</div>
</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title, size: "30x1" %>
  </div>
  <div class="field">
  	<%= f.label :tag_list, "Tags (separated by commas)"%><br>
  	<%= f.text_field :tag_list %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body, size: "30x10" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>The Ramblings are changing...</h1>

<div id="tag_cloud">
	<% tag_cloud Post.tag_counts, %w[s m l] do |tag, css_class| %>
		<%= link_to tag.name, tag_path(tag.name), class: css_class %>
	<% end %>

<% @posts.each do |post| %>
<p>
  <div class="title"><%= link_to post.title, post %><br/>
  <%= link_to post.created_at.strftime('%d/%m/%y'), post %></div>
  <div><%= post.body.html_safe %></div>  
  <div class="s">
  	(<%= raw post.tag_list.map { |t| link_to t, tag_path(t)}.join(", ")%>)</div>
  <div><%= link_to 'Edit', edit_post_path(post) %> | <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></div>
</p>
<% end %>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @post.body %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
	<div id="error_explanation">
		<div class="alert alert-danger">
			The form contains <%= pluralize(@user.errors.count, "error") %>.
		</div>
		<ul>
		<% @user.errors.full_messages.each do |m| %>
			<li><%= m %></li>
		<% end %>
		</ul>
	</div>
<% end %>